---
repos:
  # TODO(ssbarnea): add the other linters in follow-ups.
  - repo: https://github.com/python/black.git
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black>=0.1.1
        language_version: python3
