packages:
- project: ansible-config_template
  tags:
    train:
- project: ansible-pacemaker
  tags:
    train:
- project: ansible-role-atos-hsm
  tags:
    train:
- project: ansible-role-chrony
  tags:
    train:
- project: ansible-role-container-registry
  tags:
    train:
- project: ansible-role-openstack-operations
  tags:
    train:
- project: ansible-role-redhat-subscription
  tags:
    train:
- project: ansible-role-thales-hsm
  tags:
    train:
- project: ansible-role-tripleo-modify-image
  tags:
    train:
- project: aodh
  tags:
    train:
- project: aodhclient
  tags:
    train:
- project: automaton
  tags:
    train:
- project: barbican
  tags:
    train:
- project: barbican-tempest-plugin
  tags:
    train:
- project: barbicanclient
  tags:
    train:
- project: castellan
  tags:
    train:
- project: ceilometer
  tags:
    train:
- project: ceilometerclient
  tags:
    train:
      source-branch: 3ff6bac3da348bad0b220ab26eab6ad6bfbeb675
- project: ceilometermiddleware
  tags:
    train:
- project: cinder
  tags:
    train:
- project: cinder-tempest-plugin
  tags:
    train:
- project: cinderclient
  tags:
    train:
- project: cinderlib
  tags:
    train:
- project: cliff
  tags:
    train:
- project: cloudkitty
  tags:
    train:
- project: cloudkitty-dashboard
  tags:
    train:
- project: cloudkittyclient
  tags:
    train:
- project: collectd-gnocchi
  tags:
    train:
- project: congress
  tags:
    train:
- project: congress-tempest-plugin
  tags:
    train:
- project: congressclient
  tags:
    train:
- project: cursive
  tags:
    train:
- project: debtcollector
  tags:
    train:
- project: designate
  tags:
    # FIXME(ykarel) once FTBFS https://review.rdoproject.org/r/#/c/22584/
    # is fixed.
    train:
      source-branch: 4d47719b2638a96f0f2b5f71ddb0e94619fa3980
- project: designate-dashboard
  tags:
    train:
- project: designate-tempest-plugin
  tags:
    train:
- project: designateclient
  tags:
    train:
- project: dib-utils
  tags:
    train:
- project: diskimage-builder
  tags:
    train:
- project: dracclient
  tags:
    train:
- project: ec2-api
  tags:
    train:
- project: ec2api-tempest-plugin
  tags:
    train:
- project: futurist
  tags:
    train:
- project: glance
  tags:
    train:
- project: glance_store
  tags:
    train:
- project: glanceclient
  tags:
    train:
- project: glare
  tags:
    train:
- project: glareclient
  tags:
    train:
- project: gnocchi
  tags:
    train:
      source-branch: stable/4.3
- project: gnocchiclient
  tags:
    train:
- project: hacking
  tags:
    train:
- project: hardware
  tags:
    train:
- project: heat
  tags:
    train:
- project: heat-agents
  tags:
    train:
- project: heat-dashboard
  tags:
    train:
- project: heat-tempest-plugin
  tags:
    train:
- project: heat-translator
  tags:
    train:
- project: heatclient
  tags:
    train:
- project: horizon
  tags:
    train:
- project: ironic
  tags:
    train:
- project: ironic-inspector
  tags:
    train:
- project: ironic-inspector-client
  tags:
    train:
- project: ironic-lib
  tags:
    train:
- project: ironic-prometheus-exporter
  tags:
    train:
- project: ironic-python-agent
  tags:
    train:
- project: ironic-python-agent-builder
  tags:
    train:
- project: ironic-staging-drivers
  tags:
    train:
- project: ironic-tempest-plugin
  tags:
    train:
- project: ironic-ui
  tags:
    train:
- project: ironicclient
  tags:
    train:
- project: keystone
  tags:
    train:
- project: keystone-tempest-plugin
  tags:
    train:
- project: keystoneauth1
  tags:
    train:
- project: keystoneclient
  tags:
    train:
- project: keystonemiddleware
  tags:
    train:
- project: kolla
  tags:
    train:
- project: kuryr
  tags:
    train:
- project: kuryr-kubernetes
  tags:
    train:
- project: kuryr-tempest-plugin
  tags:
    train:
- project: magnum
  tags:
    train:
- project: magnum-tempest-plugin
  tags:
    train:
- project: magnum-ui
  tags:
    train:
- project: magnumclient
  tags:
    train:
- project: manila
  tags:
    train:
- project: manila-tempest-plugin
  tags:
    train:
- project: manila-ui
  tags:
    train:
- project: manilaclient
  tags:
    train:
- project: metalsmith
  tags:
    train:
- project: microversion-parse
  tags:
    train:
- project: mistral
  tags:
    train:
- project: mistral-dashboard
  tags:
    train:
- project: mistral-lib
  tags:
    train:
- project: mistral-tempest-plugin
  tags:
    train:
- project: mistralclient
  tags:
    train:
- project: monascaclient
  tags:
    train:
- project: mox3
  tags:
    train:
- project: murano
  tags:
    train:
- project: murano-agent
  tags:
    train:
- project: murano-dashboard
  tags:
    train:
- project: murano-tempest-plugin
  tags:
    train:
- project: muranoclient
  tags:
    train:
- project: networking-ansible
  tags:
    train:
- project: networking-arista
  tags:
    train:
- project: networking-bagpipe
  tags:
    train:
- project: networking-baremetal
  tags:
    train:
- project: networking-bgpvpn
  tags:
    train:
- project: networking-bigswitch
  tags:
    train:
- project: networking-fujitsu
  tags:
    train:
- project: networking-generic-switch
  tags:
    train:
- project: networking-l2gw
  tags:
    train:
- project: networking-l2gw-tempest-plugin
  tags:
    train:
- project: networking-mlnx
  tags:
    train:
- project: networking-odl
  tags:
    train:
- project: networking-ovn
  tags:
    train:
- project: networking-sfc
  tags:
    train:
- project: neutron
  tags:
    train:
- project: neutron-dynamic-routing
  tags:
    train:
- project: neutron-fwaas
  tags:
    train:
- project: neutron-lib
  tags:
    train:
- project: neutron-tempest-plugin
  tags:
    train:
- project: neutron-vpnaas
  tags:
    train:
- project: neutronclient
  tags:
    train:
- project: nova
  tags:
    train:
- project: novaclient
  tags:
    train:
- project: novajoin
  tags:
    train:
- project: novajoin-tempest-plugin
  tags:
    train:
- project: octavia
  tags:
    train:
- project: octavia-dashboard
  tags:
    train:
- project: octavia-lib
  tags:
    train:
- project: octavia-tempest-plugin
  tags:
    train:
- project: octaviaclient
  tags:
    train:
- project: openstack-macros
  tags:
    train:
- project: openstack-selinux
  tags:
    train:
- project: openstackclient
  tags:
    train:
- project: openstacksdk
  tags:
    train:
- project: os-apply-config
  tags:
    train:
- project: os-brick
  tags:
    train:
- project: os-client-config
  tags:
    train:
- project: os-collect-config
  tags:
    train:
- project: os-faults
  tags:
    train:
- project: os-ken
  tags:
    train:
- project: os-net-config
  tags:
    train:
- project: os-refresh-config
  tags:
    train:
- project: os-resource-classes
  tags:
    train:
- project: os-service-types
  tags:
    train:
- project: os-testr
  tags:
    train:
- project: os-traits
  tags:
    train:
- project: os-vif
  tags:
    train:
- project: os-win
  tags:
    train:
- project: os-xenapi
  tags:
    train:
- project: osc-lib
  tags:
    train:
- project: osc-placement
  tags:
    train:
- project: oslo-cache
  tags:
    train:
- project: oslo-concurrency
  tags:
    train:
- project: oslo-config
  tags:
    train:
- project: oslo-context
  tags:
    train:
- project: oslo-db
  tags:
    train:
- project: oslo-i18n
  tags:
    train:
- project: oslo-log
  tags:
    train:
- project: oslo-messaging
  tags:
    train:
- project: oslo-middleware
  tags:
    train:
- project: oslo-policy
  tags:
    train:
- project: oslo-privsep
  tags:
    train:
- project: oslo-reports
  tags:
    train:
- project: oslo-rootwrap
  tags:
    train:
- project: oslo-serialization
  tags:
    train:
- project: oslo-service
  tags:
    train:
- project: oslo-sphinx
  tags:
    train:
      source-branch: f92583cfc34292ec1441368f984c9692346946c4
- project: oslo-upgradecheck
  tags:
    train:
- project: oslo-utils
  tags:
    train:
- project: oslo-versionedobjects
  tags:
    train:
- project: oslo-vmware
  tags:
    train:
- project: oslotest
  tags:
    train:
- project: osops-tools-monitoring-oschecks
  tags:
    train:
- project: osprofiler
  tags:
    train:
- project: oswin-tempest-plugin
  tags:
    train:
- project: ovsdbapp
  tags:
    train:
- project: packstack
  tags:
    train:
- project: panko
  tags:
    train:
- project: pankoclient
  tags:
    train:
- project: patrole
  tags:
    train:
- project: paunch
  tags:
    train:
- project: placement
  tags:
    train:
- project: proliantutils
  tags:
    train:
- project: puppet-aodh
  tags:
    train:
- project: puppet-apache
  tags:
    train:
- project: puppet-archive
  tags:
    train:
- project: puppet-auditd
  tags:
    train:
- project: puppet-barbican
  tags:
    train:
- project: puppet-cassandra
  tags:
    train:
- project: puppet-ceilometer
  tags:
    train:
- project: puppet-ceph
  tags:
    train:
- project: puppet-certmonger
  tags:
    train:
- project: puppet-cinder
  tags:
    train:
- project: puppet-collectd
  tags:
    train:
- project: puppet-concat
  tags:
    train:
- project: puppet-congress
  tags:
    train:
- project: puppet-contrail
  tags:
    train:
- project: puppet-corosync
  tags:
    train:
- project: puppet-datacat
  tags:
    train:
- project: puppet-designate
  tags:
    train:
- project: puppet-dns
  tags:
    train:
- project: puppet-ec2api
  tags:
    train:
- project: puppet-elasticsearch
  tags:
    train:
- project: puppet-etcd
  tags:
    train:
- project: puppet-fdio
  tags:
    train:
- project: puppet-firewall
  tags:
    train:
- project: puppet-fluentd
  tags:
    train:
- project: puppet-git
  tags:
    train:
- project: puppet-glance
  tags:
    train:
- project: puppet-gnocchi
  tags:
    train:
- project: puppet-haproxy
  tags:
    train:
- project: puppet-heat
  tags:
    train:
- project: puppet-horizon
  tags:
    train:
- project: puppet-inifile
  tags:
    train:
- project: puppet-ipaclient
  tags:
    train:
- project: puppet-ironic
  tags:
    train:
- project: puppet-java
  tags:
    train:
- project: puppet-kafka
  tags:
    train:
- project: puppet-keepalived
  tags:
    train:
- project: puppet-keystone
  tags:
    train:
- project: puppet-kibana3
  tags:
    train:
- project: puppet-kmod
  tags:
    train:
- project: puppet-lib-file_concat
  tags:
    train:
- project: puppet-magnum
  tags:
    train:
- project: puppet-manila
  tags:
    train:
- project: puppet-memcached
  tags:
    train:
- project: puppet-midonet
  tags:
    train:
- project: puppet-mistral
  tags:
    train:
- project: puppet-module-data
  tags:
    train:
- project: puppet-mongodb
  tags:
    train:
- project: puppet-murano
  tags:
    train:
- project: puppet-mysql
  tags:
    train:
- project: puppet-n1k-vsm
  tags:
    train:
- project: puppet-neutron
  tags:
    train:
- project: puppet-nova
  tags:
    train:
- project: puppet-nssdb
  tags:
    train:
- project: puppet-ntp
  tags:
    train:
      source-branch: 4.2.0
- project: puppet-octavia
  tags:
    train:
- project: puppet-opendaylight
  tags:
    train:
      source-branch: stable/fluorine
- project: puppet-openstack_extras
  tags:
    train:
- project: puppet-openstacklib
  tags:
    train:
- project: puppet-oslo
  tags:
    train:
- project: puppet-ovn
  tags:
    train:
- project: puppet-pacemaker
  tags:
    train:
- project: puppet-panko
  tags:
    train:
- project: puppet-placement
  tags:
    train:
- project: puppet-powerdns
  tags:
    train:
- project: puppet-qdr
  tags:
    train:
- project: puppet-rabbitmq
  tags:
    train:
- project: puppet-redis
  tags:
    train:
- project: puppet-remote
  tags:
    train:
- project: puppet-rsync
  tags:
    train:
- project: puppet-rsyslog
  tags:
    train:
- project: puppet-sahara
  tags:
    train:
- project: puppet-sensu
  tags:
    train:
- project: puppet-snmp
  tags:
    train:
- project: puppet-ssh
  tags:
    train:
- project: puppet-staging
  tags:
    train:
- project: puppet-stdlib
  tags:
    train:
- project: puppet-swift
  tags:
    train:
- project: puppet-sysctl
  tags:
    train:
- project: puppet-systemd
  tags:
    train:
- project: puppet-tacker
  tags:
    train:
- project: puppet-tempest
  tags:
    train:
- project: puppet-timezone
  tags:
    train:
- project: puppet-tomcat
  tags:
    train:
- project: puppet-tripleo
  tags:
    train:
- project: puppet-trove
  tags:
    train:
- project: puppet-uchiwa
  tags:
    train:
- project: puppet-vcsrepo
  tags:
    train:
- project: puppet-veritas_hyperscale
  tags:
    train:
- project: puppet-vitrage
  tags:
    train:
- project: puppet-vlan
  tags:
    train:
- project: puppet-vswitch
  tags:
    train:
- project: puppet-watcher
  tags:
    train:
- project: puppet-xinetd
  tags:
    train:
- project: puppet-zaqar
  tags:
    train:
- project: puppet-zookeeper
  tags:
    train:
- project: pycadf
  tags:
    train:
- project: rally
  tags:
    train:
- project: rally-openstack
  tags:
    train:
- project: reno
  tags:
    train:
- project: requestsexceptions
  tags:
    train:
- project: rsd-lib
  tags:
    train:
- project: rsdclient
  tags:
    train:
- project: sahara
  tags:
    train:
- project: sahara-dashboard
  tags:
    train:
- project: sahara-image-elements
  tags:
    train:
- project: sahara-plugin-ambari
  tags:
    train:
- project: sahara-plugin-cdh
  tags:
    train:
- project: sahara-plugin-mapr
  tags:
    train:
- project: sahara-plugin-spark
  tags:
    train:
- project: sahara-plugin-storm
  tags:
    train:
- project: sahara-plugin-vanilla
  tags:
    train:
- project: sahara-tests
  tags:
    train:
- project: saharaclient
  tags:
    train:
- project: scciclient
  tags:
    train:
- project: senlin
  tags:
    train:
- project: senlinclient
  tags:
    train:
- project: shade
  tags:
    train:
- project: shaker
  tags:
    train:
- project: sphinx-feature-classification
  tags:
    train:
- project: stackviz
  tags:
    train:
- project: stevedore
  tags:
    train:
- project: sushy
  tags:
    train:
- project: swift
  tags:
    train:
- project: swiftclient
  tags:
    train:
- project: tacker
  tags:
    train:
- project: tackerclient
  tags:
    train:
- project: tap-as-a-service
  tags:
    train:
- project: taskflow
  tags:
    train:
- project: telemetry-tempest-plugin
  tags:
    train:
- project: tempest
  tags:
    train:
- project: tempest-horizon
  tags:
    train:
- project: tempestconf
  tags:
    train:
- project: tobiko
  tags:
    train:
- project: tooz
  tags:
    train:
- project: tripleo-ansible
  tags:
    train:
- project: tripleo-common
  tags:
    train:
- project: tripleo-common-tempest-plugin
  tags:
    train:
- project: tripleo-heat-templates
  tags:
    train:
- project: tripleo-heat-templates-compat
  tags:
    train:
      source-branch: stable/rocky
- project: tripleo-image-elements
  tags:
    train:
- project: tripleo-ipsec
  tags:
    train:
- project: tripleo-puppet-elements
  tags:
    train:
- project: tripleo-repos
  tags:
    train:
- project: tripleo-validations
  tags:
    train:
- project: tripleoclient
  tags:
    train:
- project: trove
  tags:
    train:
- project: trove-dashboard
  tags:
    train:
- project: trove-tempest-plugin
  tags:
    train:
- project: troveclient
  tags:
    train:
- project: virtualbmc
  tags:
    train:
- project: vitrage
  tags:
    train:
- project: vitrage-dashboard
  tags:
    train:
- project: vitrage-tempest-plugin
  tags:
    train:
- project: vitrageclient
  tags:
    train:
- project: vmware-nsx
  tags:
    train:
- project: vmware-nsx-tempest-plugin
  tags:
    train:
- project: vmware-nsxlib
  tags:
    train:
- project: watcher
  tags:
    train:
- project: watcher-tempest-plugin
  tags:
    train:
- project: wsme
  tags:
    train:
- project: zaqar
  tags:
    train:
- project: zaqar-tempest-plugin
  tags:
    train:
- project: zaqarclient
  tags:
    train:
