- hosts: all
  tasks:

    - name: Copy logs from workspace
      synchronize:
        src: '{{ ansible_user_dir }}/workspace/logs/'
        dest: '{{ zuul.executor.log_root }}/logs'
        mode: pull
        verify_host: true
